/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cronoslayer01;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/**
 *
 * @author CESAR
 */
public class Cronoslayer01 extends javax.swing.JFrame {

    /**
     * Creates new form Cronos
     */
    
    
    //fuente: https://www.youtube.com/watch?v=BUQcPgVTfhE
    public Cronoslayer01 {
        initComponents();
        setLocationRelativeTo(null);
        t = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ttitulo = new javax.swing.JLabel();
        jLabelTempo01 = new javax.swing.JLabel();
        jButtonInicio02 = new javax.swing.JButton();
        jButtonPausa02 = new javax.swing.JButton();
        jButtonDetener03 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ttitulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Ttitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ttitulo.setText("Cronómetro Temporizador");

        jLabelTempo01.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelTempo01.setText("00:00:00");

        jButtonInicio02.setText("Iniciar");
        jButtonInicio02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicio02ActionPerformed(evt);
            }
        });

        jButtonPausa02.setText("Pausa");
        jButtonPausa02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausa02ActionPerformed(evt);
            }
        });

        jButtonDetener03.setText("Detener");
        jButtonDetener03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetener03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTempo01, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPausa02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDetener03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonInicio02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(74, 134, Short.MAX_VALUE))
            .addComponent(Ttitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTempo01, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInicio02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPausa02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDetener03)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Timer t;
    private int h, m, s;
    private ActionListener acciones = new ActionListener() { //clase anonima
        @Override
        public void actionPerformed(ActionEvent ae) {
            s++;
            if (s == 60) {
                s = 0;
                ++m;
            }
            if (m == 60) {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
    };
    
    private void actualizarLabel(){
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s; //apli operador terneario
        jLabelTempo01.setText(tiempo);
    }
    private void jButtonInicio02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicio02ActionPerformed
        t.start();
        jButtonInicio02.setEnabled(false);
        jButtonInicio02.setText("Reanudar");
        jButtonPausa02.setEnabled(true);
        jButtonDetener03.setEnabled(true);
    }//GEN-LAST:event_jButtonInicio02ActionPerformed

    private void jButtonPausa02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausa02ActionPerformed
        t.stop();
        jButtonInicio02.setEnabled(true);
        jButtonPausa02.setEnabled(false);
    }//GEN-LAST:event_jButtonPausa02ActionPerformed

    private void jButtonDetener03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetener03ActionPerformed
        if(t.isRunning())
        {
            t.stop();
            jButtonInicio02.setEnabled(true);
        }
        jButtonInicio02.setText("Iniciar");
        jButtonPausa02.setEnabled(false);
        jButtonDetener03.setEnabled(false);
        h=0; m=0; s=0; 
        actualizarLabel();
    }//GEN-LAST:event_jButtonDetener03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronoslayer01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ttitulo;
    private javax.swing.JButton jButtonDetener03;
    private javax.swing.JButton jButtonInicio02;
    private javax.swing.JButton jButtonPausa02;
    private javax.swing.JLabel jLabelTempo01;
    // End of variables declaration//GEN-END:variables
}
