/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crono01;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/**
 *
 * @author CESAR
 */
public class Cronos extends javax.swing.JFrame {

    /**
     * Creates new form Cronos
     */
    
    
    //fuente: https://www.youtube.com/watch?v=BUQcPgVTfhE
    public Cronos() {
        initComponents();
        setLocationRelativeTo(null);
        t = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ttitulo = new javax.swing.JLabel();
        jLabelTempo01 = new javax.swing.JLabel();
        jButtonInicio01 = new javax.swing.JButton();
        jButtonPausa01 = new javax.swing.JButton();
        jButtonDetener01 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ttitulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Ttitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ttitulo.setText("Cronómetro ");
        getContentPane().add(Ttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 333, 49));

        jLabelTempo01.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelTempo01.setText("00:00:00");
        getContentPane().add(jLabelTempo01, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 116, 37));

        jButtonInicio01.setText("Iniciar");
        jButtonInicio01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicio01ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButtonPausa01.setText("Pausa");
        jButtonPausa01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausa01ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPausa01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButtonDetener01.setText("Detener");
        jButtonDetener01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetener01ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDetener01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Timer t;
    private int h, m, s;
    private ActionListener acciones = new ActionListener() { //clase anonima
        @Override
        public void actionPerformed(ActionEvent ae) {
            s++;
            if (s == 60) {
                s = 0;
                ++m;
            }
            if (m == 60) {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
    };
    
    private void actualizarLabel(){
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s; //apli operador terneario
        jLabelTempo01.setText(tiempo);
    }
    private void jButtonInicio01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicio01ActionPerformed
        t.start();
        jButtonInicio01.setEnabled(false);
        jButtonInicio01.setText("Reanudar");
        jButtonPausa01.setEnabled(true);
        jButtonDetener01.setEnabled(true);
    }//GEN-LAST:event_jButtonInicio01ActionPerformed

    private void jButtonPausa01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausa01ActionPerformed
        t.stop();
        jButtonInicio01.setEnabled(true);
        jButtonPausa01.setEnabled(false);
    }//GEN-LAST:event_jButtonPausa01ActionPerformed

    private void jButtonDetener01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetener01ActionPerformed
        if(t.isRunning())
        {
            t.stop();
            jButtonInicio01.setEnabled(true);
        }
        jButtonInicio01.setText("Iniciar");
        jButtonPausa01.setEnabled(false);
        jButtonDetener01.setEnabled(false);
        h=0; m=0; s=0; 
        actualizarLabel();
    }//GEN-LAST:event_jButtonDetener01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ttitulo;
    private javax.swing.JButton jButtonDetener01;
    private javax.swing.JButton jButtonInicio01;
    private javax.swing.JButton jButtonPausa01;
    private javax.swing.JLabel jLabelTempo01;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
